apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hello-python-deamonset
spec:
  selector:
    matchLabels:
      app: hello-python
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: hello-python
          image: akshayh7/hello-python:latest
          ports:
            - containerPort: 5000