apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  selector:
    app: hello-python
  type: NodePort
  ports:
    - name: http
      protocol: "TCP"
      port: 5000
      nodePort: 30036
      targetPort: 5000